namespace Sonda.Core;

public static partial class Strings
{
    public static readonly Dictionary<string, string> En = new(StringComparer.Ordinal)
    {
        // ---------------------------------------------------------------- general
        ["app.title"] = "Sonda — disk space",
        ["app.title.admin"] = "Sonda — disk space  (administrator)",
        ["app.name"] = "Sonda",

        // ---------------------------------------------------------------- units and formats
        ["fmt.bytes"] = "bytes",
        ["fmt.files"] = "files",
        ["fmt.minutes"] = "min",
        ["fmt.seconds"] = "s",

        // ---------------------------------------------------------------- safety
        ["safety.keep"] = "Leave alone",
        ["safety.review"] = "Your call",
        ["safety.deletable"] = "Safe to delete",

        // ---------------------------------------------------------------- families (legend)
        ["family.windows"] = "Windows",
        ["family.programs"] = "Programs",
        ["family.appdata"] = "App data and caches",
        ["family.personal"] = "Personal files",
        ["family.dev"] = "Development",
        ["family.system"] = "System files",
        ["family.virtualdisks"] = "Virtual disks",
        ["family.other"] = "Other",

        // ---------------------------------------------------------------- categories: name, what it is, how to free space
        ["cat.other.name"] = "Other",
        ["cat.other.desc"] = "Files and folders outside the standard Windows locations (folders created by hand at the root of the drive, and so on).",
        ["cat.other.action"] = "Check by hand: open the folder and see what is inside.",

        ["cat.windowsSys.name"] = "Windows system",
        ["cat.windowsSys.desc"] = "The operating system itself: System32, SysWOW64, services, fonts, .NET, recovery environment.",
        ["cat.windowsSys.action"] = "Do not delete anything by hand. Use Settings > System > Storage > Cleanup recommendations, or Disk Cleanup (cleanmgr).",

        ["cat.winSxS.name"] = "Component store (WinSxS)",
        ["cat.winSxS.desc"] = "Windows\\WinSxS: every version of the system components, including those superseded by updates. NOTE: the size shown is gross. Many files are hard links shared with System32, so the space actually used is lower (often half).",
        ["cat.winSxS.action"] = "As administrator: Dism /Online /Cleanup-Image /AnalyzeComponentStore for the real size, then Dism /Online /Cleanup-Image /StartComponentCleanup to clean up. Never delete files by hand.",

        ["cat.winUpdate.name"] = "Windows Update (downloads and cache)",
        ["cat.winUpdate.desc"] = "Windows\\SoftwareDistribution: downloaded update packages and the Windows Update database.",
        ["cat.winUpdate.action"] = "Disk Cleanup > 'Windows Update Cleanup'. Alternatively: stop the service (net stop wuauserv), empty SoftwareDistribution\\Download, start the service again.",

        ["cat.winInstaller.name"] = "Windows Installer cache (MSI)",
        ["cat.winInstaller.desc"] = "Windows\\Installer: the MSI/MSP packages of installed programs, kept so they can be repaired or uninstalled.",
        ["cat.winInstaller.action"] = "Do not delete by hand: programs would no longer uninstall. If it is huge, a tool such as PatchCleaner finds the orphaned packages.",

        ["cat.winTemp.name"] = "System temporary files",
        ["cat.winTemp.desc"] = "Windows\\Temp, CbsTemp and similar: working files of installations and updates.",
        ["cat.winTemp.action"] = "Settings > System > Storage > Temporary files, or empty Windows\\Temp (files in use are skipped).",

        ["cat.logs.name"] = "Logs, dumps and error reports",
        ["cat.logs.desc"] = "Setup and update logs, memory dumps (MEMORY.DMP, Minidump), Windows Error Reporting, ETL traces.",
        ["cat.logs.action"] = "Disk Cleanup > 'System error memory dump files' and 'Error reporting files'. The .log and .dmp files can be deleted.",

        ["cat.drivers.name"] = "Driver store (DriverStore)",
        ["cat.drivers.desc"] = "Windows\\System32\\DriverStore: every installed driver, including old versions (GPU drivers above all).",
        ["cat.drivers.action"] = "Do not delete by hand. pnputil /enum-drivers lists the packages; tools such as DriverStore Explorer remove the old duplicates.",

        ["cat.windowsOld.name"] = "Previous installation (Windows.old)",
        ["cat.windowsOld.desc"] = "The previous version of Windows, kept for ten days after a feature update so you can roll back.",
        ["cat.windowsOld.action"] = "Disk Cleanup > 'Previous Windows installation(s)', or Settings > Storage > Temporary files.",

        ["cat.pageFile.name"] = "Virtual memory (pagefile.sys)",
        ["cat.pageFile.desc"] = "The paging file: RAM extended onto the disk. Windows sizes it according to how much RAM you have.",
        ["cat.pageFile.action"] = "Do not delete. To shrink it: Advanced system settings > Performance > Virtual memory (leaving it automatic is usually best).",

        ["cat.hiberfil.name"] = "Hibernation (hiberfil.sys)",
        ["cat.hiberfil.desc"] = "A copy of RAM used for hibernation and fast startup: roughly as big as the installed memory.",
        ["cat.hiberfil.action"] = "If you never hibernate: as administrator 'powercfg /h off' removes it (you also lose fast startup). 'powercfg /h /type reduced' halves it while keeping fast startup.",

        ["cat.swapFile.name"] = "App swap (swapfile.sys)",
        ["cat.swapFile.desc"] = "Swap file used by Microsoft Store apps. Usually small.",
        ["cat.swapFile.action"] = "Managed by Windows, nothing to do.",

        ["cat.recycleBin.name"] = "Recycle Bin",
        ["cat.recycleBin.desc"] = "Files deleted but not yet removed from the disk ($Recycle.Bin).",
        ["cat.recycleBin.action"] = "Empty the Recycle Bin (right-click the icon > Empty Recycle Bin).",

        ["cat.restorePoints.name"] = "Restore points and shadow copies",
        ["cat.restorePoints.desc"] = "System Volume Information: restore points, shadow copies (previous versions of files), system indexes and databases. Readable only as administrator.",
        ["cat.restorePoints.action"] = "System Protection (sysdm.cpl) > Configure > 'Delete', or reduce the reserved space. As administrator: vssadmin delete shadows /for=C: /oldest.",

        ["cat.programs.name"] = "Installed programs",
        ["cat.programs.desc"] = "Program Files and Program Files (x86): programs installed for every user.",
        ["cat.programs.action"] = "Uninstall the ones you do not use from Settings > Apps > Installed apps. Do not delete the folders by hand.",

        ["cat.userPrograms.name"] = "Programs installed for this user",
        ["cat.userPrograms.desc"] = "AppData\\Local\\Programs: programs installed only for your account (VS Code, Discord, Signal, and so on).",
        ["cat.userPrograms.action"] = "Uninstall from Settings > Apps.",

        ["cat.storeApps.name"] = "Microsoft Store apps and their data",
        ["cat.storeApps.desc"] = "WindowsApps (the apps themselves) and AppData\\Local\\Packages (data and caches of Store and system apps).",
        ["cat.storeApps.action"] = "Uninstall apps from Settings > Apps. The subfolders of Packages hold app data: use 'Reset' in the app's Advanced options.",

        ["cat.installerCache.name"] = "Installer caches",
        ["cat.installerCache.desc"] = "ProgramData\\Package Cache (Visual Studio, .NET, SQL: installers kept for repairs) and extracted installer folders at the root of the drive (NVIDIA, AMD, Intel).",
        ["cat.installerCache.action"] = "The NVIDIA/AMD/Intel folders at the root can be deleted once installation is done. Package Cache cannot: use the Visual Studio Installer to remove workloads.",

        ["cat.games.name"] = "Games",
        ["cat.games.desc"] = "Steam, Epic Games, GOG and Xbox libraries, plus 'Games' folders.",
        ["cat.games.action"] = "Uninstall games from their launcher (Steam > Manage > Uninstall), not by hand.",

        ["cat.appData.name"] = "Application data and caches",
        ["cat.appData.desc"] = "AppData (Local, Roaming, LocalLow) and ProgramData: settings, databases, models and caches of installed programs.",
        ["cat.appData.action"] = "Look at which application weighs most: it often has a cache you can clear from its own settings (Teams, Spotify, Slack, editors...).",

        ["cat.caches.name"] = "Browser and app caches",
        ["cat.caches.desc"] = "Caches of Chrome, Edge, Firefox, Brave, Opera, and app caches (Code Cache, GPUCache, shader caches, INetCache).",
        ["cat.caches.action"] = "In the browser: Clear browsing data > 'Cached images and files'. Cache folders can be deleted with the program closed: they are recreated.",

        ["cat.userTemp.name"] = "User temporary files",
        ["cat.userTemp.desc"] = "AppData\\Local\\Temp: working files left behind by installers and programs.",
        ["cat.userTemp.action"] = "Settings > Storage > Temporary files, or empty %TEMP% by hand (files in use are skipped).",

        ["cat.devCaches.name"] = "Package manager caches",
        ["cat.devCaches.desc"] = "Local caches of npm, pip, NuGet, Gradle, Maven, Cargo, Go, pnpm, Yarn, uv/poetry: downloaded packages, all re-downloadable.",
        ["cat.devCaches.action"] = "npm cache clean --force  ·  pip cache purge  ·  dotnet nuget locals all --clear  ·  yarn cache clean  ·  pnpm store prune  ·  Gradle: delete ~\\.gradle\\caches",

        ["cat.devBuild.name"] = "Project dependencies and build output",
        ["cat.devBuild.desc"] = "node_modules and build/obj/.vs/_deps folders: recreated by building again or by npm install.",
        ["cat.devBuild.action"] = "Delete node_modules and the build folders of projects you are not working on; they are regenerated when needed.",

        ["cat.gitRepos.name"] = "Git repositories (.git)",
        ["cat.gitRepos.desc"] = "The full history of cloned repositories.",
        ["cat.gitRepos.action"] = "Run git gc --aggressive in the repository, or delete clones you no longer need.",

        ["cat.devSdk.name"] = "SDKs and development tools",
        ["cat.devSdk.desc"] = "Android SDK, emulator system images, toolchains, JDKs.",
        ["cat.devSdk.action"] = "In SDK Manager remove system images, emulators and platform versions you do not use.",

        ["cat.virtualDisks.name"] = "Virtual disks (VMs, WSL, Docker)",
        ["cat.virtualDisks.desc"] = "Files .vhdx/.vhd/.vmdk/.vdi: disks of virtual machines, WSL and Docker Desktop. They grow with use and do NOT shrink on their own when you delete files inside them.",
        ["cat.virtualDisks.action"] = "WSL: wsl --shutdown, then compact the vhdx (Optimize-VHD or diskpart 'compact vdisk'). Docker: docker system prune -a. VMs: compact the disk from the VM manager.",

        ["cat.diskImages.name"] = "Disk images and ISOs",
        ["cat.diskImages.desc"] = "Files .iso, .img, .wim, .esd: installation media and disk images.",
        ["cat.diskImages.action"] = "Delete the ISOs you have already used or can download again.",

        ["cat.downloads.name"] = "Downloads",
        ["cat.downloads.desc"] = "The Downloads folder: installers, archives and downloaded files that are usually no longer needed.",
        ["cat.downloads.action"] = "Delete installers (.exe/.msi) and archives you have already used; move elsewhere whatever you want to keep.",

        ["cat.personal.name"] = "Documents and personal files",
        ["cat.personal.desc"] = "Documents, Pictures, Videos, Music, Desktop.",
        ["cat.personal.action"] = "Move to an external drive or to the cloud whatever you do not need at hand; videos are almost always the heaviest item.",

        ["cat.oneDrive.name"] = "OneDrive",
        ["cat.oneDrive.desc"] = "The OneDrive folder: files marked 'Always keep on this device' use local space; 'online-only' files do not.",
        ["cat.oneDrive.action"] = "Right-click files or folders > 'Free up space' to keep them in the cloud only.",

        ["cat.userOther.name"] = "User profile (other)",
        ["cat.userOther.desc"] = "Other folders inside C:\\Users\\<user> (projects, folders created by hand, tool caches).",
        ["cat.userOther.action"] = "Check by hand what they contain.",

        ["cat.mail.name"] = "Outlook mail (.pst/.ost)",
        ["cat.mail.desc"] = "Outlook mail archives and offline caches.",
        ["cat.mail.action"] = "In Outlook reduce the 'Mail to keep offline' period, or archive old folders.",

        ["cat.archives.name"] = "Compressed archives",
        ["cat.archives.desc"] = "Loose .zip, .7z, .rar, .tar.gz files.",
        ["cat.archives.action"] = "Delete the archives you have already extracted.",

        ["cat.searchIndex.name"] = "Windows Search index",
        ["cat.searchIndex.desc"] = "ProgramData\\Microsoft\\Search: the file indexing database.",
        ["cat.searchIndex.action"] = "Do not delete by hand. Indexing Options > Advanced > Rebuild, or index fewer locations.",

        ["cat.fonts.name"] = "Fonts",
        ["cat.fonts.desc"] = "Installed typefaces (Windows\\Fonts).",
        ["cat.fonts.action"] = "Uninstall fonts you do not use from Settings > Personalization > Fonts.",

        // ---------------------------------------------------------------- file types
        ["type.unknown.label"] = "File",
        ["type.unknown.detail"] = "File of an unrecognised type",
        ["type.unknown.ext"] = "{0} file (unrecognised type)",
        ["type.noext.label"] = "File without extension",
        ["type.noext.detail"] = "File without extension",
        ["type.virtualdisk.label"] = "Virtual disk",
        ["type.virtualdisk.detail"] = "Virtual machine, WSL or Docker disk (.vhdx/.vhd/.vmdk/.vdi)",
        ["type.diskimage.label"] = "Disk image",
        ["type.diskimage.detail"] = "Disk or installation image (.iso/.img/.wim/.esd)",
        ["type.mail.label"] = "Mail archive",
        ["type.mail.detail"] = "Outlook archive (.pst/.ost)",
        ["type.archive.label"] = "Compressed archive",
        ["type.archive.detail"] = "Compressed archive (.zip/.7z/.rar/.tar.gz)",
        ["type.log.label"] = "Log",
        ["type.log.detail"] = "Log file",
        ["type.dump.label"] = "Memory dump",
        ["type.dump.detail"] = "Memory dump written after a crash (.dmp)",
        ["type.registry.label"] = "Registry",
        ["type.registry.detail"] = "Windows registry hive or its transaction log: do not delete",
        ["type.video.label"] = "Video",
        ["type.video.detail"] = "Video file",
        ["type.audio.label"] = "Audio",
        ["type.audio.detail"] = "Audio file",
        ["type.audioproject.label"] = "Audio project",
        ["type.audioproject.detail"] = "Project or session of music software",
        ["type.samples.label"] = "Samples / audio libraries",
        ["type.samples.detail"] = "Sound and sample libraries",
        ["type.image.label"] = "Image",
        ["type.image.detail"] = "Image file",
        ["type.document.label"] = "Document",
        ["type.document.detail"] = "Document",
        ["type.program.label"] = "Program (executable)",
        ["type.program.detail"] = "Executable program or installer",
        ["type.library.label"] = "Library / component",
        ["type.library.detail"] = "Program library (DLL, component, driver)",
        ["type.package.label"] = "Package",
        ["type.package.detail"] = "Program package or module",
        ["type.database.label"] = "Database",
        ["type.database.detail"] = "Database file",
        ["type.source.label"] = "Source code",
        ["type.source.detail"] = "Source code file",
        ["type.font.label"] = "Font",
        ["type.font.detail"] = "Typeface",
        ["type.backup.label"] = "Backup",
        ["type.backup.detail"] = "Backup copy",
        ["type.temp.label"] = "Temporary file",
        ["type.temp.detail"] = "Temporary or partial file",
        ["type.ml.label"] = "AI model / ML data",
        ["type.ml.detail"] = "Machine learning model or weights",
        ["type.game.label"] = "Game (assets)",
        ["type.game.detail"] = "Game asset or archive",
        ["type.vmconfig.label"] = "Virtual machine (config)",
        ["type.vmconfig.detail"] = "Virtual machine configuration or state file",
        ["type.system.label"] = "System",
        ["type.system.detail"] = "System file",
        ["type.container.label"] = "Docker/OCI container",
        ["type.container.detail"] = "Container layer or image",
        ["type.subtitles.label"] = "Subtitles / text",
        ["type.subtitles.detail"] = "Subtitles or plain text",
        ["type.shortcut.label"] = "Shortcut",
        ["type.shortcut.detail"] = "Shortcut to another file",
        ["ext.none"] = "(none)",
        ["type.folder"] = "Folder",
        ["type.link"] = "Link",
        ["type.link.detail"] = "Junction or symbolic link",

        // ---------------------------------------------------------------- header
        ["ui.folderButton"] = "Folder…",
        ["ui.folderButton.tip"] = "Analyse a single folder instead of the whole drive",
        ["ui.scan"] = "Analyse",
        ["ui.stop"] = "Stop",
        ["ui.stopping"] = "Stopping…",
        ["ui.elevate"] = "Restart as administrator",
        ["ui.elevate.tip"] = "To read System Volume Information, other user profiles and shadow copies",
        ["ui.export"] = "Export ▾",
        ["ui.export.text"] = "Full report (text)…",
        ["ui.export.files"] = "Biggest files (CSV)…",
        ["ui.export.dirs"] = "Folders (CSV)…",
        ["ui.export.causes"] = "Causes (CSV)…",
        ["ui.settings"] = "Settings",
        ["ui.ready"] = "Choose a drive and press Analyse.",
        ["ui.readyFor"] = "Ready to analyse {0}",
        ["ui.readyForFolder"] = "Ready to analyse the folder {0}",
        ["ui.pickFolder"] = "Choose the folder to analyse",
        ["ui.folderPrefix"] = "Folder:  ",
        ["ui.localDisk"] = "Local disk",
        ["ui.driveUsedOf"] = "{0} used of {1}",

        // ---------------------------------------------------------------- progress and status
        ["ui.scanning"] = "Analysing…",
        ["ui.processing"] = "Working out the results…",
        ["ui.done"] = "Done.  ",
        ["ui.cancelled"] = "Stopped: partial data.  ",
        ["ui.progress"] = "{0} files  ·  {1} folders  ·  {2}  ·  {3}",
        ["ui.progress.denied"] = "  ·  {0} not accessible",
        ["ui.doneStats"] = "{0} files, {1} folders in {2}",
        ["ui.doneDenied"] = "  ·  {0} folders not accessible",
        ["ui.status.done"] = "Analysis complete.",
        ["ui.status.cancelled"] = "Analysis stopped: the numbers are partial.",
        ["ui.status.error"] = "Something went wrong during the analysis.",
        ["ui.status.ready"] = "Ready.",
        ["ui.status.right"] = "{0} files · {1} on disk",
        ["ui.status.admin"] = " · administrator",
        ["ui.error"] = "Error: {0}",

        // ---------------------------------------------------------------- volume bar
        ["ui.volume.line"] = "{0}   {1} used of {2} ({3})   ·   {4} free",
        ["ui.volume.folder"] = "Folder {0}   {1} on disk   ·   volume {2}: {3} free of {4}",
        ["ui.volume.right"] = "found in files: {0}   ·   cluster {1} bytes   ·   {2}",
        ["ui.volume.rightFolder"] = "{0} files · {1} folders",
        ["ui.volume.seenTip"] = "The share of used space that the scan attributed to files",

        // ---------------------------------------------------------------- administrator banner
        ["ui.adminBanner"] = "You are not running as administrator: System Volume Information (restore points), other users' profiles and some system folders cannot be read. Their space will show up as 'unattributed'.",

        // ---------------------------------------------------------------- causes column
        ["ui.mainCause"] = "Main cause",
        ["ui.mainCause.empty"] = "This is where the biggest space eater will appear, with an explanation of what it is and how to free it up.",
        ["ui.otherCauses"] = "Other causes, heaviest first",
        ["ui.whatIsIt"] = "What it is",
        ["ui.howToFree"] = "How to free space",
        ["ui.topFolders"] = "Heaviest folders",
        ["ui.seeDetail"] = "See the full detail",
        ["ui.shareOfUsed"] = " of the used space",
        ["ui.shareOfFolder"] = " of the folder",
        ["ui.legend"] = "Legend",
        ["ui.legend.note"] = "Sizes are 'on disk' (the space actually used, rounded up to the cluster; compressed files and online-only cloud files count for what they really take).",
        ["ui.nFiles"] = "{0} files",

        // ---------------------------------------------------------------- tabs
        ["tab.folders"] = "Folders",
        ["tab.biggestFiles"] = "Biggest files",
        ["tab.causeDetail"] = "Cause detail",
        ["tab.fileTypes"] = "File types",
        ["tab.balance"] = "Balance",

        // ---------------------------------------------------------------- folders tab
        ["ui.back"] = "Back",
        ["ui.up"] = "Parent folder",
        ["ui.openInExplorer"] = "Open in File Explorer",
        ["ui.dirSummary"] = "{0} on disk · {1} files · {2} folders · {3}",
        ["ui.dirSummary.denied"] = " · {0} not accessible",
        ["ui.treemapHint"] = "Map of this folder  ·  each rectangle is proportional to the space used; click to select, double-click to enter",
        ["ui.treemap.empty"] = "No data",
        ["ui.treemap.other"] = "other",

        // ---------------------------------------------------------------- columns
        ["col.name"] = "Name",
        ["col.onDisk"] = "On disk",
        ["col.share"] = "Share",
        ["col.files"] = "Files",
        ["col.type"] = "Type",
        ["col.category"] = "Category",
        ["col.categoryCause"] = "Category (cause)",
        ["col.safety"] = "Safety",
        ["col.modified"] = "Modified",
        ["col.size"] = "Size",
        ["col.notes"] = "Notes",
        ["col.folder"] = "Folder",
        ["col.whatIsIt"] = "What it is",
        ["col.path"] = "Path",
        ["col.causeShare"] = "Share of cause",
        ["col.description"] = "Description",
        ["col.topExtensions"] = "Heaviest extensions",
        ["col.item"] = "Item",
        ["col.bytes"] = "Bytes",
        ["col.explanation"] = "Explanation",

        // ---------------------------------------------------------------- row notes
        ["note.reparse"] = "Junction or link: the content is counted where it really lives",
        ["note.denied"] = "Access denied: contents unknown",
        ["note.error"] = "Error: {0}",
        ["note.cloud"] = "Cloud file: only the downloaded part uses space",
        ["note.compressed"] = "NTFS compressed",
        ["note.sparse"] = "Sparse file",
        ["note.deniedShort"] = "access denied",
        ["note.reparseShort"] = "link",
        ["note.reparseCsv"] = "junction/link (not followed)",
        ["tip.dir"] = "{0}\n{1} on disk  ·  {2} files\n{3}",
        ["tip.file"] = "{0}\n{1} on disk ({2} logical)\n{3}\n{4}",

        // ---------------------------------------------------------------- biggest files
        ["ui.filter"] = "Filter:",
        ["ui.filter.tip"] = "Search in the name or the path",
        ["ui.allCategories"] = "All categories",
        ["ui.deleteSelected"] = "Delete selected (Recycle Bin)…",
        ["ui.filesSummary"] = "{0} files shown (of the {1} biggest) · {2}",
        ["ui.typeSummary"] = "Type “{0}”: the {1} biggest files · {2}",

        // ---------------------------------------------------------------- cause detail
        ["ui.causeStats"] = "{0} · {1} files · rank {2} of {3}",
        ["ui.causeAction"] = "How to free space: {0}",
        ["ui.causeGroups"] = "Heaviest folders in this cause  ·  double-click to enter",
        ["ui.causeFiles"] = "Biggest files in this cause",

        // ---------------------------------------------------------------- file types
        ["ui.typesHint"] = "What the space-eating files actually are, wherever they live. Double-click a type to see its biggest files.",

        // ---------------------------------------------------------------- balance
        ["ui.balanceHint"] = "The reckoning: the space Windows calls 'used' against what the scan found. The difference tells you how much sits in places that cannot be read (restore points, other profiles) or in metadata.",
        ["ui.deniedNone"] = "No inaccessible folders",
        ["ui.deniedList"] = "Inaccessible folders ({0})",

        ["bal.used"] = "Space used on the volume",
        ["bal.used.note"] = "Total {0}, free {1}. This is the number Windows reports.",
        ["bal.found"] = "Files found (on disk)",
        ["bal.found.note"] = "{0} files in {1} folders. Logical size {2}: the difference is the rounding up to the cluster ({3} bytes) minus compressed and sparse files.",
        ["bal.cancelled"] = "Scan stopped",
        ["bal.cancelled.note"] = "The files found are partial, so the balance cannot add up. Run a full analysis for an answer.",
        ["bal.mft"] = "NTFS metadata (MFT)",
        ["bal.mft.note"] = "The file table: about 1 KB per file and folder. Real figure read from the volume.",
        ["bal.mftEst"] = "NTFS metadata (MFT, estimate)",
        ["bal.mftEst.note"] = "Estimate: 1 KB per file and folder (the real figure can only be read as administrator).",
        ["bal.fsMeta"] = "File system metadata ({0})",
        ["bal.fsMeta.note"] = "On a non-NTFS volume the metadata is not estimated; it is usually negligible.",
        ["bal.shadow"] = "Shadow copies / restore points",
        ["bal.shadow.unknown"] = "Not determined.",
        ["bal.denied"] = "Inaccessible folders ({0})",
        ["bal.denied.admin"] = "Contents unknown even as administrator (folders protected by the system).",
        ["bal.denied.user"] = "Contents unknown: System Volume Information, other users' profiles, protected folders. Restart as administrator to read them.",
        ["bal.reparse"] = "Junctions and links skipped ({0})",
        ["bal.reparse.note"] = "They point to other folders: the content is counted where it really lives (or on another volume). It is not extra space.",
        ["bal.cloud"] = "Online-only cloud files ({0})",
        ["bal.cloud.note"] = "OneDrive and similar placeholders: counted for the space they really take on the disk (often zero).",
        ["bal.unattributed"] = "Unattributed",
        ["bal.unattributed.denied"] = "Almost certainly inside the {0} inaccessible folders{1}{2} The rest is partial clusters, folder indexes and files held open exclusively.",
        ["bal.unattributed.hints"] = " (e.g. {0})",
        ["bal.unattributed.elevate"] = ": restart as administrator to attribute it.",
        ["bal.unattributed.dot"] = ".",
        ["bal.unattributed.small"] = "Normal: partial clusters, folder indexes, files held open exclusively, space that changed during the scan.",
        ["bal.unattributed.big"] = "Space that cannot be attributed to files: shadow copies not read, files held open exclusively, or space that changed during the scan.",
        ["bal.over"] = "Counted more than the used space",
        ["bal.over.note"] = "Normal on Windows: hard links make the same file appear in several folders (WinSxS and System32 share thousands of files). The real figure is the volume's used space; the Windows entries should be read as an upper bound.",
        ["bal.folder"] = "Folder analysed",
        ["bal.folder.note"] = "Note",
        ["bal.folder.noteText"] = "The full balance (volume used space against space found) is only available when analysing a whole volume.",

        // ---------------------------------------------------------------- shadow copies
        ["shadow.wmi"] = "From WMI (Win32_ShadowStorage).",
        ["shadow.none.admin"] = "No shadow copies hosted on this volume.",
        ["shadow.none"] = "No shadow copies on this volume (or the figure is not available without privileges).",
        ["shadow.noVolume"] = "Shadow copies: volume not found in WMI.",
        ["shadow.needAdmin"] = "Shadow copies: restart as administrator to read this figure.",
        ["shadow.wmiError"] = "Shadow copies: WMI did not answer ({0}).",
        ["shadow.error"] = "Shadow copies: cannot be determined ({0})",

        // ---------------------------------------------------------------- context menu
        ["menu.open"] = "Open in File Explorer",
        ["menu.reveal"] = "Show in folder",
        ["menu.enter"] = "Enter folder (in Sonda)",
        ["menu.copyPath"] = "Copy path",
        ["menu.properties"] = "Properties",
        ["menu.delete"] = "Delete (to Recycle Bin)…",

        // ---------------------------------------------------------------- deletion
        ["del.title"] = "Sonda — delete",
        ["del.busy"] = "Wait for the analysis to finish before deleting.",
        ["del.noRoot"] = "The root of the analysis cannot be deleted here: delete the subfolders or the individual files.",
        ["del.group"] = "“{0}” holds files of this cause but other things too (or it is the root of the analysis): it cannot be deleted as a whole.\n\nEnter the folder and choose what to delete.",
        ["del.nItems"] = "{0} items",
        ["del.question"] = "Send {0} ({1}) to the Recycle Bin?\n\n",
        ["del.more"] = "  …and {0} more\n",
        ["del.keepWarn"] = "WARNING: {0} of these belong to categories to LEAVE ALONE ({1}). Deleting them can break Windows or your programs.\n\n",
        ["del.footer"] = "This is the only confirmation. Items go to the Recycle Bin and can be restored from there (if they are too big for the Bin, Windows warns you before deleting them for good).",
        ["del.selectFirst"] = "Select one or more files in the table first.",
        ["del.done"] = "Deleted {0} items ({1}) — now in the Recycle Bin.",
        ["del.recalcError"] = "Error while recalculating: {0}",

        // ---------------------------------------------------------------- shell errors
        ["shell.cancelled"] = "Operation cancelled.",
        ["shell.sameFile"] = "Source and destination are the same.",
        ["shell.manySrc"] = "Several sources for a single destination.",
        ["shell.diffVolumes"] = "The folders are on different volumes.",
        ["shell.rootDir"] = "The root of a drive cannot be deleted.",
        ["shell.userCancel"] = "Cancelled by the user.",
        ["shell.destSubtree"] = "The destination is a subfolder of the source.",
        ["shell.accessSrc"] = "Access to the source denied: restart as administrator, or the file is protected.",
        ["shell.pathTooDeep"] = "Path too long.",
        ["shell.badPath"] = "Invalid path or drive.",
        ["shell.invalidFiles"] = "Invalid path.",
        ["shell.sameDest"] = "The destination is the same as the source.",
        ["shell.exists"] = "The file already exists at the destination.",
        ["shell.destIsFolder"] = "The destination is a folder, not a file.",
        ["shell.nameTooLong"] = "File name too long.",
        ["shell.readOnly"] = "The disk is read-only.",
        ["shell.tooBig"] = "The file is larger than the file system allows.",
        ["shell.srcError"] = "Error accessing the source.",
        ["shell.dstError"] = "Error accessing the destination.",
        ["shell.inUse2"] = "The file is in use by another program, or the operation is not allowed.",
        ["shell.diskError"] = "Disk read/write error.",
        ["shell.denied"] = "Access denied: restart as administrator.",
        ["shell.notFound"] = "File not found (perhaps already deleted).",
        ["shell.inUse"] = "The file is in use by another program.",
        ["shell.generic"] = "Shell error (code 0x{0}).",

        // ---------------------------------------------------------------- exports
        ["exp.title"] = "Export",
        ["exp.text"] = "Text (*.txt)|*.txt",
        ["exp.csv"] = "CSV (*.csv)|*.csv",
        ["exp.saved"] = "Report saved: {0}",
        ["exp.savedCsv"] = "CSV saved: {0}",
        ["exp.copied"] = "Path copied: {0}",

        // ---------------------------------------------------------------- settings
        ["settings.title"] = "Settings",
        ["settings.lang"] = "Language",
        ["settings.lang.auto"] = "Automatic",
        ["settings.lang.note"] = "Changing the language updates the interface straight away: the analysis you already ran is kept.",
        ["settings.about"] = "Sonda {0} — disk space analyser\nMIT · StarVerb Audio",
        ["settings.close"] = "Close",

        // ---------------------------------------------------------------- CSV
        ["csv.files"] = "Name;Folder;On disk (bytes);On disk;Size (bytes);Type;What it is;Category;Safety;Modified;Full path",
        ["csv.dirs"] = "Folder;On disk (bytes);On disk;Size (bytes);Files;Subfolders;Category;Safety;Notes;Full path",
        ["csv.causes"] = "Rank;Cause;On disk (bytes);On disk;Share;Files;What it is;How to free space;Safety",

        // ---------------------------------------------------------------- text report
        ["rep.title"] = "SONDA - disk space report",
        ["rep.scanned"] = "Analysed: {0}   on {1}   in {2}",
        ["rep.volume"] = "Volume {0} ({1}): total {2}, used {3} ({4}), free {5}",
        ["rep.found"] = "Found {0} files in {1} folders: {2} on disk ({3} logical)",
        ["rep.denied"] = "Inaccessible folders: {0}",
        ["rep.denied.hint"] = "  (run as administrator to read them)",
        ["rep.cancelled"] = "WARNING: scan stopped, partial data.",
        ["rep.mainCause"] = "MAIN CAUSE",
        ["rep.mainLine"] = "  {0}: {1} ({2} {3}), {4} files",
        ["rep.ofUsed"] = "of the used space",
        ["rep.ofFolder"] = "of the analysed folder",
        ["rep.whatIs"] = "  What it is: {0}",
        ["rep.howTo"] = "  How to free space: {0}",
        ["rep.safety"] = "  Safety: {0}",
        ["rep.topFolders"] = "  Heaviest folders:",
        ["rep.otherCauses"] = "OTHER CAUSES (heaviest first)",
        ["rep.topFiles"] = "THE {0} BIGGEST FILES",
        ["rep.types"] = "FILE TYPES",
        ["rep.balance"] = "BALANCE",
        ["rep.deniedList"] = "INACCESSIBLE FOLDERS",
        ["rep.andMore"] = "  ... and {0} more",
        ["rep.cliScanning"] = "Sonda: analysing {0} ...",
        ["rep.cliDone"] = "Sonda: done in {0} ({1} files).",
    };
}
