namespace Sonda.Core;

/// <summary>
/// Tutte le stringhe mostrate all'utente, per lingua. Le chiavi sono uguali nei due dizionari:
/// se una manca in inglese si ripiega automaticamente sull'italiano (vedi Loc.S).
/// </summary>
public static partial class Strings
{
    public static readonly Dictionary<string, string> It = new(StringComparer.Ordinal)
    {
        // ---------------------------------------------------------------- generale
        ["app.title"] = "Sonda — spazio su disco",
        ["app.title.admin"] = "Sonda — spazio su disco  (amministratore)",
        ["app.name"] = "Sonda",

        // ---------------------------------------------------------------- unità e formati
        ["fmt.bytes"] = "byte",
        ["fmt.files"] = "file",
        ["fmt.minutes"] = "min",
        ["fmt.seconds"] = "s",

        // ---------------------------------------------------------------- sicurezza
        ["safety.keep"] = "Non toccare",
        ["safety.review"] = "Da valutare",
        ["safety.deletable"] = "Eliminabile",

        // ---------------------------------------------------------------- famiglie (legenda)
        ["family.windows"] = "Windows",
        ["family.programs"] = "Programmi",
        ["family.appdata"] = "Dati app e cache",
        ["family.personal"] = "File personali",
        ["family.dev"] = "Sviluppo",
        ["family.system"] = "File di sistema",
        ["family.virtualdisks"] = "Dischi virtuali",
        ["family.other"] = "Altro",

        // ---------------------------------------------------------------- categorie: nome, cos'è, come liberare
        ["cat.other.name"] = "Altro",
        ["cat.other.desc"] = "File e cartelle fuori dai posti standard di Windows (cartelle create a mano alla radice, ecc.).",
        ["cat.other.action"] = "Controlla a mano: apri la cartella e guarda cosa contiene.",

        ["cat.windowsSys.name"] = "Sistema Windows",
        ["cat.windowsSys.desc"] = "Il sistema operativo: System32, SysWOW64, servizi, font, .NET, ambiente di ripristino.",
        ["cat.windowsSys.action"] = "Non eliminare nulla a mano. Usa Impostazioni > Sistema > Archiviazione > Consigli per la pulizia, oppure Pulizia disco (cleanmgr).",

        ["cat.winSxS.name"] = "Archivio componenti (WinSxS)",
        ["cat.winSxS.desc"] = "Windows\\WinSxS: tutte le versioni dei componenti di sistema, comprese quelle sostituite dagli aggiornamenti. ATTENZIONE: la dimensione mostrata è lorda. Molti file sono hard link condivisi con System32, quindi lo spazio davvero occupato è inferiore (spesso la metà).",
        ["cat.winSxS.action"] = "Da amministratore: Dism /Online /Cleanup-Image /AnalyzeComponentStore per la dimensione reale, poi Dism /Online /Cleanup-Image /StartComponentCleanup per pulire. Mai eliminare file a mano.",

        ["cat.winUpdate.name"] = "Windows Update (download e cache)",
        ["cat.winUpdate.desc"] = "Windows\\SoftwareDistribution: pacchetti di aggiornamento scaricati e il database di Windows Update.",
        ["cat.winUpdate.action"] = "Pulizia disco > 'Pulizia di Windows Update'. In alternativa: ferma il servizio (net stop wuauserv), svuota SoftwareDistribution\\Download, riavvia il servizio.",

        ["cat.winInstaller.name"] = "Installer di Windows (MSI)",
        ["cat.winInstaller.desc"] = "Windows\\Installer: i pacchetti MSI/MSP dei programmi installati, conservati per poterli riparare o disinstallare.",
        ["cat.winInstaller.action"] = "Non eliminare a mano: i programmi non si disinstallerebbero più. Se è enorme, uno strumento come PatchCleaner individua i pacchetti orfani.",

        ["cat.winTemp.name"] = "File temporanei di sistema",
        ["cat.winTemp.desc"] = "Windows\\Temp, CbsTemp e simili: file di lavoro di installazioni e aggiornamenti.",
        ["cat.winTemp.action"] = "Impostazioni > Sistema > Archiviazione > File temporanei, oppure svuota Windows\\Temp (i file in uso vengono saltati).",

        ["cat.logs.name"] = "Log, dump e segnalazioni errori",
        ["cat.logs.desc"] = "Log di installazione e aggiornamento, dump di memoria (MEMORY.DMP, Minidump), Windows Error Reporting, tracce ETL.",
        ["cat.logs.action"] = "Pulizia disco > 'File di dump della memoria' e 'File di segnalazione errori'. I file .log e .dmp si possono eliminare.",

        ["cat.drivers.name"] = "Archivio driver (DriverStore)",
        ["cat.drivers.desc"] = "Windows\\System32\\DriverStore: tutti i driver installati, comprese le versioni vecchie (soprattutto GPU).",
        ["cat.drivers.action"] = "Non eliminare a mano. pnputil /enum-drivers elenca i pacchetti; strumenti come DriverStore Explorer rimuovono i duplicati vecchi.",

        ["cat.windowsOld.name"] = "Installazione precedente (Windows.old)",
        ["cat.windowsOld.desc"] = "La versione precedente di Windows, tenuta dieci giorni dopo un aggiornamento importante per poter tornare indietro.",
        ["cat.windowsOld.action"] = "Pulizia disco > 'Installazioni precedenti di Windows', oppure Impostazioni > Archiviazione > File temporanei.",

        ["cat.pageFile.name"] = "Memoria virtuale (pagefile.sys)",
        ["cat.pageFile.desc"] = "File di paging: è l'estensione della RAM su disco. Windows ne decide la dimensione in base alla RAM.",
        ["cat.pageFile.action"] = "Non eliminare. Per ridurlo: Impostazioni avanzate di sistema > Prestazioni > Memoria virtuale (meglio lasciarlo automatico).",

        ["cat.hiberfil.name"] = "Ibernazione (hiberfil.sys)",
        ["cat.hiberfil.desc"] = "Copia della memoria RAM usata per l'ibernazione e per l'avvio rapido: è grande circa quanto la RAM.",
        ["cat.hiberfil.action"] = "Se non usi l'ibernazione: da amministratore 'powercfg /h off' lo elimina (perdi anche l'avvio rapido). 'powercfg /h /type reduced' lo dimezza tenendo l'avvio rapido.",

        ["cat.swapFile.name"] = "Swap delle app (swapfile.sys)",
        ["cat.swapFile.desc"] = "File di scambio usato dalle app di Microsoft Store. Di solito piccolo.",
        ["cat.swapFile.action"] = "Gestito da Windows, non serve intervenire.",

        ["cat.recycleBin.name"] = "Cestino",
        ["cat.recycleBin.desc"] = "File eliminati ma non ancora rimossi dal disco ($Recycle.Bin).",
        ["cat.recycleBin.action"] = "Svuota il Cestino (tasto destro sull'icona > Svuota cestino).",

        ["cat.restorePoints.name"] = "Punti di ripristino e copie shadow",
        ["cat.restorePoints.desc"] = "System Volume Information: punti di ripristino, copie shadow (versioni precedenti dei file), indice e database di sistema. Leggibile solo da amministratore.",
        ["cat.restorePoints.action"] = "Protezione sistema (sysdm.cpl) > Configura > 'Elimina' o riduci lo spazio riservato. Da amministratore: vssadmin delete shadows /for=C: /oldest.",

        ["cat.programs.name"] = "Programmi installati",
        ["cat.programs.desc"] = "Program Files e Program Files (x86): i programmi installati per tutti gli utenti.",
        ["cat.programs.action"] = "Disinstalla da Impostazioni > App > App installate quelli che non usi. Non eliminare le cartelle a mano.",

        ["cat.userPrograms.name"] = "Programmi installati per l'utente",
        ["cat.userPrograms.desc"] = "AppData\\Local\\Programs: programmi installati solo per il tuo utente (VS Code, Discord, Signal, ecc.).",
        ["cat.userPrograms.action"] = "Disinstalla da Impostazioni > App.",

        ["cat.storeApps.name"] = "App di Microsoft Store e loro dati",
        ["cat.storeApps.desc"] = "WindowsApps (le app) e AppData\\Local\\Packages (dati e cache delle app dello Store e di sistema).",
        ["cat.storeApps.action"] = "Disinstalla le app da Impostazioni > App. Le sottocartelle di Packages contengono i dati delle app: 'Reimposta' l'app dalle sue Opzioni avanzate.",

        ["cat.installerCache.name"] = "Cache di installer",
        ["cat.installerCache.desc"] = "ProgramData\\Package Cache (Visual Studio, .NET, SQL: installer conservati per riparazioni) e cartelle di installer estratti alla radice (NVIDIA, AMD, Intel).",
        ["cat.installerCache.action"] = "Le cartelle NVIDIA/AMD/Intel alla radice si possono eliminare a installazione finita. Package Cache no: usa Visual Studio Installer per rimuovere carichi di lavoro.",

        ["cat.games.name"] = "Giochi",
        ["cat.games.desc"] = "Librerie di Steam, Epic Games, GOG, Xbox e cartelle 'Games'.",
        ["cat.games.action"] = "Disinstalla i giochi dal loro launcher (Steam > Gestisci > Disinstalla), non a mano.",

        ["cat.appData.name"] = "Dati e cache delle applicazioni",
        ["cat.appData.desc"] = "AppData (Local, Roaming, LocalLow) e ProgramData: impostazioni, database, modelli, cache dei programmi installati.",
        ["cat.appData.action"] = "Guarda quale applicazione pesa di più: spesso ha una cache svuotabile dalle sue impostazioni (Teams, Spotify, Slack, editor...).",

        ["cat.caches.name"] = "Cache di browser e app",
        ["cat.caches.desc"] = "Cache di Chrome, Edge, Firefox, Brave, Opera e cache di app (Code Cache, GPUCache, shader cache, INetCache).",
        ["cat.caches.action"] = "Nel browser: Cancella dati di navigazione > 'Immagini e file memorizzati nella cache'. Le cartelle Cache si possono eliminare a programma chiuso: si ricreano.",

        ["cat.userTemp.name"] = "File temporanei utente",
        ["cat.userTemp.desc"] = "AppData\\Local\\Temp: file di lavoro lasciati da installer e programmi.",
        ["cat.userTemp.action"] = "Impostazioni > Archiviazione > File temporanei, oppure svuota %TEMP% a mano (i file in uso vengono saltati).",

        ["cat.devCaches.name"] = "Cache di pacchetti di sviluppo",
        ["cat.devCaches.desc"] = "Cache locali di npm, pip, NuGet, Gradle, Maven, Cargo, Go, pnpm, Yarn, uv/poetry: pacchetti scaricati, riscaricabili.",
        ["cat.devCaches.action"] = "npm cache clean --force  ·  pip cache purge  ·  dotnet nuget locals all --clear  ·  yarn cache clean  ·  pnpm store prune  ·  Gradle: elimina ~\\.gradle\\caches",

        ["cat.devBuild.name"] = "Dipendenze e build dei progetti",
        ["cat.devBuild.desc"] = "node_modules, cartelle build/obj/.vs/_deps: si ricreano compilando o con npm install.",
        ["cat.devBuild.action"] = "Elimina node_modules e le cartelle di build dei progetti che non stai usando; si rigenerano quando servono.",

        ["cat.gitRepos.name"] = "Repository Git (.git)",
        ["cat.gitRepos.desc"] = "Cronologia completa dei repository clonati.",
        ["cat.gitRepos.action"] = "git gc --aggressive nel repository, oppure elimina i cloni che non ti servono più.",

        ["cat.devSdk.name"] = "SDK e strumenti di sviluppo",
        ["cat.devSdk.desc"] = "Android SDK, immagini di sistema degli emulatori, toolchain, JDK.",
        ["cat.devSdk.action"] = "Da SDK Manager rimuovi immagini di sistema, emulatori e versioni di piattaforma che non usi.",

        ["cat.virtualDisks.name"] = "Dischi virtuali (VM, WSL, Docker)",
        ["cat.virtualDisks.desc"] = "File .vhdx/.vhd/.vmdk/.vdi: dischi di macchine virtuali, di WSL e di Docker Desktop. Crescono con l'uso e NON si restringono da soli quando cancelli dentro.",
        ["cat.virtualDisks.action"] = "WSL: wsl --shutdown poi compatta il vhdx (Optimize-VHD o diskpart 'compact vdisk'). Docker: docker system prune -a. VM: compatta il disco dal gestore VM.",

        ["cat.diskImages.name"] = "Immagini disco e ISO",
        ["cat.diskImages.desc"] = "File .iso, .img, .wim, .esd: immagini di installazione e dischi.",
        ["cat.diskImages.action"] = "Elimina le ISO che hai già usato o che puoi riscaricare.",

        ["cat.downloads.name"] = "Download",
        ["cat.downloads.desc"] = "La cartella Download: installer, archivi e file scaricati che spesso non servono più.",
        ["cat.downloads.action"] = "Elimina gli installer (.exe/.msi) e gli archivi già usati; sposta altrove quello che vuoi tenere.",

        ["cat.personal.name"] = "Documenti e file personali",
        ["cat.personal.desc"] = "Documenti, Immagini, Video, Musica, Desktop.",
        ["cat.personal.action"] = "Sposta su un disco esterno o nel cloud ciò che non ti serve a portata di mano; i video sono quasi sempre la voce più pesante.",

        ["cat.oneDrive.name"] = "OneDrive",
        ["cat.oneDrive.desc"] = "Cartella OneDrive: i file 'sempre disponibili su questo dispositivo' occupano spazio locale; quelli 'solo online' no.",
        ["cat.oneDrive.action"] = "Tasto destro sui file/cartelle > 'Libera spazio' per tenerli solo nel cloud.",

        ["cat.userOther.name"] = "Profilo utente (altro)",
        ["cat.userOther.desc"] = "Altre cartelle dentro C:\\Users\\<utente> (progetti, cartelle create a mano, .cache di strumenti).",
        ["cat.userOther.action"] = "Controlla a mano cosa contengono.",

        ["cat.mail.name"] = "Posta di Outlook (.pst/.ost)",
        ["cat.mail.desc"] = "Archivi e cache della posta di Outlook.",
        ["cat.mail.action"] = "In Outlook riduci il periodo di 'Posta da tenere offline' o archivia le cartelle vecchie.",

        ["cat.archives.name"] = "Archivi compressi",
        ["cat.archives.desc"] = "File .zip, .7z, .rar, .tar.gz sparsi.",
        ["cat.archives.action"] = "Elimina gli archivi già estratti.",

        ["cat.searchIndex.name"] = "Indice di ricerca di Windows",
        ["cat.searchIndex.desc"] = "ProgramData\\Microsoft\\Search: il database dell'indicizzazione dei file.",
        ["cat.searchIndex.action"] = "Non eliminare a mano. Opzioni di indicizzazione > Avanzate > Ricostruisci, o riduci le posizioni indicizzate.",

        ["cat.fonts.name"] = "Font",
        ["cat.fonts.desc"] = "Caratteri installati (Windows\\Fonts).",
        ["cat.fonts.action"] = "Disinstalla i font che non usi da Impostazioni > Personalizzazione > Tipi di carattere.",

        // ---------------------------------------------------------------- tipi di file
        ["type.unknown.label"] = "File",
        ["type.unknown.detail"] = "File di tipo non riconosciuto",
        ["type.unknown.ext"] = "File {0} (tipo non riconosciuto)",
        ["type.noext.label"] = "File senza estensione",
        ["type.noext.detail"] = "File senza estensione",
        ["type.virtualdisk.label"] = "Disco virtuale",
        ["type.virtualdisk.detail"] = "Disco di macchina virtuale, WSL o Docker (.vhdx/.vhd/.vmdk/.vdi)",
        ["type.diskimage.label"] = "Immagine disco",
        ["type.diskimage.detail"] = "Immagine di disco o di installazione (.iso/.img/.wim/.esd)",
        ["type.mail.label"] = "Archivio di posta",
        ["type.mail.detail"] = "Archivio Outlook (.pst/.ost)",
        ["type.archive.label"] = "Archivio compresso",
        ["type.archive.detail"] = "Archivio compresso (.zip/.7z/.rar/.tar.gz)",
        ["type.log.label"] = "Log",
        ["type.log.detail"] = "File di registro (log)",
        ["type.dump.label"] = "Dump di memoria",
        ["type.dump.detail"] = "Dump di memoria dopo un errore (.dmp)",
        ["type.registry.label"] = "Registro di sistema",
        ["type.registry.detail"] = "Hive del registro di Windows o suo log transazionale: non eliminare",
        ["type.video.label"] = "Video",
        ["type.video.detail"] = "File video",
        ["type.audio.label"] = "Audio",
        ["type.audio.detail"] = "File audio",
        ["type.audioproject.label"] = "Progetto audio",
        ["type.audioproject.detail"] = "Progetto/sessione di software musicale",
        ["type.samples.label"] = "Campioni / librerie audio",
        ["type.samples.detail"] = "Librerie di suoni e campioni",
        ["type.image.label"] = "Immagine",
        ["type.image.detail"] = "File immagine",
        ["type.document.label"] = "Documento",
        ["type.document.detail"] = "Documento",
        ["type.program.label"] = "Programma (eseguibile)",
        ["type.program.detail"] = "Programma eseguibile o installer",
        ["type.library.label"] = "Libreria / componente",
        ["type.library.detail"] = "Libreria di programma (DLL, componente, driver)",
        ["type.package.label"] = "Pacchetto",
        ["type.package.detail"] = "Pacchetto o modulo di programma",
        ["type.database.label"] = "Database",
        ["type.database.detail"] = "File di database",
        ["type.source.label"] = "Codice sorgente",
        ["type.source.detail"] = "File di codice sorgente",
        ["type.font.label"] = "Font",
        ["type.font.detail"] = "Tipo di carattere",
        ["type.backup.label"] = "Backup",
        ["type.backup.detail"] = "Copia di sicurezza",
        ["type.temp.label"] = "File temporaneo",
        ["type.temp.detail"] = "File temporaneo o parziale",
        ["type.ml.label"] = "Modello di IA / dati ML",
        ["type.ml.detail"] = "Modello o pesi di machine learning",
        ["type.game.label"] = "Gioco (risorse)",
        ["type.game.detail"] = "Risorsa o archivio di gioco",
        ["type.vmconfig.label"] = "Macchina virtuale (config)",
        ["type.vmconfig.detail"] = "File di configurazione/stato di macchina virtuale",
        ["type.system.label"] = "Sistema",
        ["type.system.detail"] = "File di sistema",
        ["type.container.label"] = "Contenitore Docker/OCI",
        ["type.container.detail"] = "Livello o immagine di contenitore",
        ["type.subtitles.label"] = "Sottotitoli / testo",
        ["type.subtitles.detail"] = "Sottotitoli o testo semplice",
        ["type.shortcut.label"] = "Collegamento",
        ["type.shortcut.detail"] = "Collegamento a un altro file",
        ["ext.none"] = "(nessuna)",
        ["type.folder"] = "Cartella",
        ["type.link"] = "Collegamento",
        ["type.link.detail"] = "Giunzione o collegamento simbolico",

        // ---------------------------------------------------------------- intestazione
        ["ui.folderButton"] = "Cartella…",
        ["ui.folderButton.tip"] = "Analizza una sola cartella invece dell'intero disco",
        ["ui.scan"] = "Analizza",
        ["ui.stop"] = "Ferma",
        ["ui.stopping"] = "Fermo…",
        ["ui.elevate"] = "Riavvia come amministratore",
        ["ui.elevate.tip"] = "Per leggere System Volume Information, gli altri profili e le copie shadow",
        ["ui.export"] = "Esporta ▾",
        ["ui.export.text"] = "Rapporto completo (testo)…",
        ["ui.export.files"] = "File più grandi (CSV)…",
        ["ui.export.dirs"] = "Cartelle (CSV)…",
        ["ui.export.causes"] = "Cause (CSV)…",
        ["ui.settings"] = "Impostazioni",
        ["ui.ready"] = "Scegli il disco e premi Analizza.",
        ["ui.readyFor"] = "Pronto ad analizzare {0}",
        ["ui.readyForFolder"] = "Pronto ad analizzare la cartella {0}",
        ["ui.pickFolder"] = "Scegli la cartella da analizzare",
        ["ui.folderPrefix"] = "Cartella:  ",
        ["ui.localDisk"] = "Disco locale",
        ["ui.driveUsedOf"] = "{0} usati di {1}",

        // ---------------------------------------------------------------- avanzamento e stato
        ["ui.scanning"] = "Analisi in corso…",
        ["ui.processing"] = "Elaboro i risultati…",
        ["ui.done"] = "Fatto.  ",
        ["ui.cancelled"] = "Interrotta: dati parziali.  ",
        ["ui.progress"] = "{0} file  ·  {1} cartelle  ·  {2}  ·  {3}",
        ["ui.progress.denied"] = "  ·  {0} non accessibili",
        ["ui.doneStats"] = "{0} file, {1} cartelle in {2}",
        ["ui.doneDenied"] = "  ·  {0} cartelle non accessibili",
        ["ui.status.done"] = "Analisi completata.",
        ["ui.status.cancelled"] = "Analisi interrotta: i numeri sono parziali.",
        ["ui.status.error"] = "Errore durante l'analisi.",
        ["ui.status.ready"] = "Pronto.",
        ["ui.status.right"] = "{0} file · {1} su disco",
        ["ui.status.admin"] = " · amministratore",
        ["ui.error"] = "Errore: {0}",

        // ---------------------------------------------------------------- barra del volume
        ["ui.volume.line"] = "{0}   {1} usati su {2} ({3})   ·   {4} liberi",
        ["ui.volume.folder"] = "Cartella {0}   {1} su disco   ·   volume {2}: {3} liberi su {4}",
        ["ui.volume.right"] = "trovati in file: {0}   ·   cluster {1} byte   ·   {2}",
        ["ui.volume.rightFolder"] = "{0} file · {1} cartelle",
        ["ui.volume.seenTip"] = "Parte dello spazio usato che la scansione ha attribuito a file",

        // ---------------------------------------------------------------- avviso amministratore
        ["ui.adminBanner"] = "Non sei amministratore: System Volume Information (punti di ripristino), i profili degli altri utenti e alcune cartelle di sistema non si possono leggere. Il loro spazio comparirà come 'non attribuito'.",

        // ---------------------------------------------------------------- colonna cause
        ["ui.mainCause"] = "Causa principale",
        ["ui.mainCause.empty"] = "Qui comparirà la voce che occupa più spazio, con la spiegazione di cos'è e di come liberarlo.",
        ["ui.otherCauses"] = "Altre cause, in ordine di peso",
        ["ui.whatIsIt"] = "Cos'è",
        ["ui.howToFree"] = "Come liberare spazio",
        ["ui.topFolders"] = "Pesano di più",
        ["ui.seeDetail"] = "Vedi tutto il dettaglio",
        ["ui.shareOfUsed"] = " dello spazio usato",
        ["ui.shareOfFolder"] = " della cartella",
        ["ui.legend"] = "Legenda",
        ["ui.legend.note"] = "Le dimensioni sono 'su disco' (spazio davvero occupato, arrotondato al cluster; i file compressi e quelli solo online del cloud contano per quello che occupano).",
        ["ui.nFiles"] = "{0} file",

        // ---------------------------------------------------------------- schede
        ["tab.folders"] = "Cartelle",
        ["tab.biggestFiles"] = "File più grandi",
        ["tab.causeDetail"] = "Dettaglio causa",
        ["tab.fileTypes"] = "Tipi di file",
        ["tab.balance"] = "Bilancio",

        // ---------------------------------------------------------------- scheda cartelle
        ["ui.back"] = "Indietro",
        ["ui.up"] = "Cartella superiore",
        ["ui.openInExplorer"] = "Apri in Esplora risorse",
        ["ui.dirSummary"] = "{0} su disco · {1} file · {2} cartelle · {3}",
        ["ui.dirSummary.denied"] = " · {0} non accessibili",
        ["ui.treemapHint"] = "Mappa della cartella  ·  ogni rettangolo è proporzionale allo spazio; clic per selezionare, doppio clic per entrare",
        ["ui.treemap.empty"] = "Nessun dato",
        ["ui.treemap.other"] = "altro",

        // ---------------------------------------------------------------- colonne
        ["col.name"] = "Nome",
        ["col.onDisk"] = "Su disco",
        ["col.share"] = "Quota",
        ["col.files"] = "File",
        ["col.type"] = "Tipo",
        ["col.category"] = "Categoria",
        ["col.categoryCause"] = "Categoria (causa)",
        ["col.safety"] = "Sicurezza",
        ["col.modified"] = "Modificato",
        ["col.size"] = "Dimensione",
        ["col.notes"] = "Note",
        ["col.folder"] = "Cartella",
        ["col.whatIsIt"] = "Cos'è",
        ["col.path"] = "Percorso",
        ["col.causeShare"] = "Quota causa",
        ["col.description"] = "Descrizione",
        ["col.topExtensions"] = "Estensioni più pesanti",
        ["col.item"] = "Voce",
        ["col.bytes"] = "Byte",
        ["col.explanation"] = "Spiegazione",

        // ---------------------------------------------------------------- note delle righe
        ["note.reparse"] = "Giunzione/collegamento: il contenuto è contato altrove",
        ["note.denied"] = "Accesso negato: contenuto sconosciuto",
        ["note.error"] = "Errore: {0}",
        ["note.cloud"] = "File cloud: occupa solo lo spazio scaricato",
        ["note.compressed"] = "Compresso da NTFS",
        ["note.sparse"] = "File sparse",
        ["note.deniedShort"] = "accesso negato",
        ["note.reparseShort"] = "collegamento",
        ["note.reparseCsv"] = "giunzione/collegamento (non seguito)",
        ["tip.dir"] = "{0}\n{1} su disco  ·  {2} file\n{3}",
        ["tip.file"] = "{0}\n{1} su disco ({2} logici)\n{3}\n{4}",

        // ---------------------------------------------------------------- file più grandi
        ["ui.filter"] = "Filtra:",
        ["ui.filter.tip"] = "Cerca nel nome o nel percorso",
        ["ui.allCategories"] = "Tutte le categorie",
        ["ui.deleteSelected"] = "Elimina selezionati (Cestino)…",
        ["ui.filesSummary"] = "{0} file mostrati (fra i {1} più grandi) · {2}",
        ["ui.typeSummary"] = "Tipo “{0}”: i {1} file più grandi · {2}",

        // ---------------------------------------------------------------- dettaglio causa
        ["ui.causeStats"] = "{0} · {1} file · posizione {2} su {3}",
        ["ui.causeAction"] = "Come liberare spazio: {0}",
        ["ui.causeGroups"] = "Cartelle che pesano di più in questa causa  ·  doppio clic per entrare",
        ["ui.causeFiles"] = "File più grandi in questa causa",

        // ---------------------------------------------------------------- tipi di file
        ["ui.typesHint"] = "Cosa sono i file che occupano spazio, indipendentemente da dove stanno. Doppio clic su un tipo per vedere i suoi file più grandi.",

        // ---------------------------------------------------------------- bilancio
        ["ui.balanceHint"] = "Il conto della serva: lo spazio che Windows dice 'usato' contro quello che la scansione ha trovato. La differenza dice quanto sta in posti non leggibili (punti di ripristino, altri profili) o in metadati.",
        ["ui.deniedNone"] = "Nessuna cartella non accessibile",
        ["ui.deniedList"] = "Cartelle non accessibili ({0})",

        ["bal.used"] = "Spazio usato sul volume",
        ["bal.used.note"] = "Totale {0}, liberi {1}. È il numero di Windows.",
        ["bal.found"] = "File trovati (su disco)",
        ["bal.found.note"] = "{0} file in {1} cartelle. Dimensione logica {2}: la differenza è l'arrotondamento al cluster ({3} byte) meno i file compressi/sparse.",
        ["bal.cancelled"] = "Scansione interrotta",
        ["bal.cancelled.note"] = "I file trovati sono parziali: il bilancio non torna per costruzione. Rilancia l'analisi completa per una risposta.",
        ["bal.mft"] = "Metadati NTFS (MFT)",
        ["bal.mft.note"] = "Tabella dei file: circa 1 KB per ogni file e cartella. Dato reale letto dal volume.",
        ["bal.mftEst"] = "Metadati NTFS (MFT, stima)",
        ["bal.mftEst.note"] = "Stima: 1 KB per ogni file e cartella (il dato reale si legge solo da amministratore).",
        ["bal.fsMeta"] = "Metadati del file system ({0})",
        ["bal.fsMeta.note"] = "Su un volume non NTFS i metadati non si stimano; di solito sono trascurabili.",
        ["bal.shadow"] = "Copie shadow / punti di ripristino",
        ["bal.shadow.unknown"] = "Non determinato.",
        ["bal.denied"] = "Cartelle non accessibili ({0})",
        ["bal.denied.admin"] = "Contenuto sconosciuto anche da amministratore (cartelle protette dal sistema).",
        ["bal.denied.user"] = "Contenuto sconosciuto: System Volume Information, profili di altri utenti, cartelle protette. Riavvia come amministratore per leggerle.",
        ["bal.reparse"] = "Giunzioni e collegamenti saltati ({0})",
        ["bal.reparse.note"] = "Puntano ad altre cartelle: il contenuto è contato dove sta davvero (o su un altro volume). Non è spazio in più.",
        ["bal.cloud"] = "File cloud solo online ({0})",
        ["bal.cloud.note"] = "Segnaposto di OneDrive & simili: contati per lo spazio che occupano davvero sul disco (spesso zero).",
        ["bal.unattributed"] = "Non attribuito",
        ["bal.unattributed.denied"] = "Sta quasi certamente nelle {0} cartelle non accessibili{1}{2} Il resto sono cluster parziali, indici delle cartelle e file aperti in esclusiva.",
        ["bal.unattributed.hints"] = " (es. {0})",
        ["bal.unattributed.elevate"] = ": riavvia come amministratore per attribuirlo.",
        ["bal.unattributed.dot"] = ".",
        ["bal.unattributed.small"] = "Fisiologico: cluster parziali, indici delle cartelle, file aperti in esclusiva, spazio cambiato durante la scansione.",
        ["bal.unattributed.big"] = "Spazio non attribuibile a file: copie shadow non lette, file aperti in modo esclusivo, o spazio cambiato durante la scansione.",
        ["bal.over"] = "Contato più dello spazio usato",
        ["bal.over.note"] = "Normale su Windows: gli hard link fanno comparire lo stesso file in più cartelle (WinSxS e System32 condividono migliaia di file). Lo spazio reale è quello usato dal volume; le voci Windows sono da leggere come limite superiore.",
        ["bal.folder"] = "Cartella analizzata",
        ["bal.folder.note"] = "Nota",
        ["bal.folder.noteText"] = "Il bilancio completo (spazio usato del volume contro spazio trovato) è disponibile solo analizzando l'intero volume.",

        // ---------------------------------------------------------------- copie shadow
        ["shadow.wmi"] = "Da WMI (Win32_ShadowStorage).",
        ["shadow.none.admin"] = "Nessuna copia shadow ospitata su questo volume.",
        ["shadow.none"] = "Nessuna copia shadow su questo volume (o dato non disponibile senza privilegi).",
        ["shadow.noVolume"] = "Copie shadow: volume non trovato in WMI.",
        ["shadow.needAdmin"] = "Copie shadow: serve avviare come amministratore per leggere il dato.",
        ["shadow.wmiError"] = "Copie shadow: WMI non ha risposto ({0}).",
        ["shadow.error"] = "Copie shadow: non determinabile ({0})",

        // ---------------------------------------------------------------- menu contestuale
        ["menu.open"] = "Apri in Esplora risorse",
        ["menu.reveal"] = "Mostra nella cartella",
        ["menu.enter"] = "Entra nella cartella (in Sonda)",
        ["menu.copyPath"] = "Copia percorso",
        ["menu.properties"] = "Proprietà",
        ["menu.delete"] = "Elimina (nel Cestino)…",

        // ---------------------------------------------------------------- eliminazione
        ["del.title"] = "Sonda — elimina",
        ["del.busy"] = "Attendi la fine dell'analisi prima di eliminare.",
        ["del.noRoot"] = "La radice dell'analisi non si elimina da qui: elimina le sottocartelle o i singoli file.",
        ["del.group"] = "“{0}” contiene file di questa causa ma anche altro (o è la radice dell'analisi): non si elimina in blocco.\n\nEntra nella cartella e scegli cosa eliminare.",
        ["del.nItems"] = "{0} elementi",
        ["del.question"] = "Mandare nel Cestino {0} ({1})?\n\n",
        ["del.more"] = "  …e altri {0}\n",
        ["del.keepWarn"] = "ATTENZIONE: {0} di questi appartengono a categorie da NON toccare ({1}). Eliminarli può rompere Windows o i programmi.\n\n",
        ["del.footer"] = "Questa è l'unica conferma. Gli elementi finiscono nel Cestino, da cui si possono recuperare (se troppo grandi per il Cestino, Windows avvisa prima di eliminarli definitivamente).",
        ["del.selectFirst"] = "Seleziona prima uno o più file nella tabella.",
        ["del.done"] = "Eliminati {0} elementi ({1}) — nel Cestino.",
        ["del.recalcError"] = "Errore nel ricalcolo: {0}",

        // ---------------------------------------------------------------- errori della shell
        ["shell.cancelled"] = "Operazione annullata.",
        ["shell.sameFile"] = "Origine e destinazione coincidono.",
        ["shell.manySrc"] = "Più origini per una sola destinazione.",
        ["shell.diffVolumes"] = "Le cartelle sono su volumi diversi.",
        ["shell.rootDir"] = "Non si può eliminare la radice di un disco.",
        ["shell.userCancel"] = "Annullato dall'utente.",
        ["shell.destSubtree"] = "La destinazione è una sottocartella dell'origine.",
        ["shell.accessSrc"] = "Accesso negato all'origine: serve avviare come amministratore o il file è protetto.",
        ["shell.pathTooDeep"] = "Percorso troppo lungo.",
        ["shell.badPath"] = "Percorso non valido o unità inesistente.",
        ["shell.invalidFiles"] = "Percorso non valido.",
        ["shell.sameDest"] = "La destinazione è uguale all'origine.",
        ["shell.exists"] = "Il file esiste già nella destinazione.",
        ["shell.destIsFolder"] = "La destinazione è una cartella, non un file.",
        ["shell.nameTooLong"] = "Nome file troppo lungo.",
        ["shell.readOnly"] = "Il disco è in sola lettura.",
        ["shell.tooBig"] = "Il file è più grande di quanto il file system ammetta.",
        ["shell.srcError"] = "Errore di accesso all'origine.",
        ["shell.dstError"] = "Errore di accesso alla destinazione.",
        ["shell.inUse2"] = "Il file è in uso da un altro programma o l'operazione non è ammessa.",
        ["shell.diskError"] = "Errore di lettura/scrittura del disco.",
        ["shell.denied"] = "Accesso negato: serve avviare come amministratore.",
        ["shell.notFound"] = "File non trovato (forse già eliminato).",
        ["shell.inUse"] = "Il file è in uso da un altro programma.",
        ["shell.generic"] = "Errore della shell (codice 0x{0}).",

        // ---------------------------------------------------------------- esportazioni
        ["exp.title"] = "Esporta",
        ["exp.text"] = "Testo (*.txt)|*.txt",
        ["exp.csv"] = "CSV (*.csv)|*.csv",
        ["exp.saved"] = "Rapporto salvato: {0}",
        ["exp.savedCsv"] = "CSV salvato: {0}",
        ["exp.copied"] = "Percorso copiato: {0}",

        // ---------------------------------------------------------------- impostazioni
        ["settings.title"] = "Impostazioni",
        ["settings.lang"] = "Lingua",
        ["settings.lang.auto"] = "Automatica",
        ["settings.lang.note"] = "Cambiando lingua l'interfaccia si aggiorna subito: l'analisi già fatta resta.",
        ["settings.about"] = "Sonda {0} — analisi dello spazio su disco\nMIT · StarVerb Audio",
        ["settings.close"] = "Chiudi",

        // ---------------------------------------------------------------- CSV
        ["csv.files"] = "Nome;Cartella;Su disco (byte);Su disco;Dimensione (byte);Tipo;Cos'è;Categoria;Sicurezza;Modificato;Percorso completo",
        ["csv.dirs"] = "Cartella;Su disco (byte);Su disco;Dimensione (byte);File;Sottocartelle;Categoria;Sicurezza;Note;Percorso completo",
        ["csv.causes"] = "Posizione;Causa;Su disco (byte);Su disco;Quota;File;Cos'è;Come liberare;Sicurezza",

        // ---------------------------------------------------------------- rapporto di testo
        ["rep.title"] = "SONDA - rapporto sullo spazio occupato",
        ["rep.scanned"] = "Analizzato: {0}   il {1}   in {2}",
        ["rep.volume"] = "Volume {0} ({1}): totale {2}, usati {3} ({4}), liberi {5}",
        ["rep.found"] = "Trovati {0} file in {1} cartelle: {2} su disco ({3} logici)",
        ["rep.denied"] = "Cartelle non accessibili: {0}",
        ["rep.denied.hint"] = "  (avvia come amministratore per leggerle)",
        ["rep.cancelled"] = "ATTENZIONE: scansione interrotta, dati parziali.",
        ["rep.mainCause"] = "CAUSA PRINCIPALE",
        ["rep.mainLine"] = "  {0}: {1} ({2} {3}), {4} file",
        ["rep.ofUsed"] = "dello spazio usato",
        ["rep.ofFolder"] = "della cartella analizzata",
        ["rep.whatIs"] = "  Cos'è: {0}",
        ["rep.howTo"] = "  Come liberare: {0}",
        ["rep.safety"] = "  Sicurezza: {0}",
        ["rep.topFolders"] = "  Cartelle che pesano di più:",
        ["rep.otherCauses"] = "ALTRE CAUSE (in ordine di peso)",
        ["rep.topFiles"] = "I {0} FILE PIÙ GRANDI",
        ["rep.types"] = "TIPI DI FILE",
        ["rep.balance"] = "BILANCIO",
        ["rep.deniedList"] = "CARTELLE NON ACCESSIBILI",
        ["rep.andMore"] = "  ... e altre {0}",
        ["rep.cliScanning"] = "Sonda: analisi di {0} ...",
        ["rep.cliDone"] = "Sonda: fatto in {0} ({1} file).",
    };
}
